[[language]]
name = "nix"
auto-format = true
formatter = { command = "alejandra", args = ["-q"] }

[[language]]
name = "go"
formatter = { command = "goimports" }

# go install golang.org/x/tools/cmd/goimports@latest
# go install golang.org/x/tools/gopls@latest
# go install github.com/go-delve/delve/cmd/dlv@latest
# go install honnef.co/go/tools/cmd/staticcheck@latest
[language-server.gopls]
config = { "local" = "goimports", "staticcheck" = true, "verboseOutput" = true, "analyses" = { unusedparams = true, useany = true } }

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
linkedProjects = [ "Cargo.toml", "fuzz/Cargo.toml" ]
cargo = { features = "all" }
