[[language]]
name = "nix"
auto-format = true
formatter = { command = "alejandra", args = ["-q"] }

[language-server.rust-analyzer]
command = "rust-analyzer"

# [language-server.rust-analyzer.config]
# linkedProjects = [ "Cargo.toml", "fuzz/Cargo.toml" ]
# cargo = { features = "all" }
