[[language]]
name = "nix"
auto-format = true
formatter = { command = "alejandra", args = ["-q"] }

[[language]]
name = "rust"
language-server.environment = {"JANUS_INTEROP_CONTAINER" = "skip"}
language-server.command = "rust-analyzer"