source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

plug "whereswaldon/shellcheck.kak"

plug "andreyorst/kaktree" defer kaktree %{
    set-option global kaktree_double_click_duration '0.5'
    set-option global kaktree_dir_icon_open  '▾ 🗁 '
    set-option global kaktree_dir_icon_close '▸ 🗀 '
    set-option global kaktree_file_icon      '⠀⠀🖺'
} config %{
    hook global WinSetOption filetype=kaktree %{
        remove-highlighter buffer/numbers
        remove-highlighter buffer/matching
        remove-highlighter buffer/wrap
        remove-highlighter buffer/show-whitespaces
    }
    kaktree-enable
}

add-highlighter global/ number-lines
add-highlighter global/ wrap

colorscheme tomorrow-night
face global Default default,default
face global LineNumbers default,default+fgd@LineNumbers
face global BufferPadding default,default

eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable

set global autoreload true
set global tabstop 4
set global indentwidth 0

hook global WinSetOption filetype=(go|c|cpp|java|python|rust) %{
    set-option window lsp_auto_highlight_references true
    set-option window lsp_hover_anchor false
    lsp-auto-hover-enable
    echo -debug "Enabling LSP for filetype %opt{filetype}"
}

set global lsp_diagnostic_line_error_sign '║'
set global lsp_diagnostic_line_warning_sign '┊'
map -docstring "lsp mode" global user l ':enter-user-mode lsp<ret>'
map -docstring "lsp rename" global user r ':lsp-rename-prompt<ret>'

hook global KakEnd .* lsp-exit

define-command -override -hidden lsp-show-error -params 1 -docstring "Render error (suppress useless gopls errors)" %{
    evaluate-commands %sh{
        if [ "$1" = "go language server error: 'no object found'" ]; then
            exit 0
        fi
        echo 'echo -debug "kak-lsp:" %arg{1}'
        echo 'info %arg{1}'
    }
}

hook global WinSetOption filetype=go %{
	set-option window formatcmd 'goimports'
    hook buffer BufWritePre .* %{
	    format
    }
}

hook global WinSetOption filetype=python %{
    map window insert <s-tab> '<a-;>    '
    map window insert <tab> '<a-;>    '
    set window indentwidth 4
    set-option window formatcmd 'autopep8 -aaa -'
    set-option window lintcmd %{ run() { pylint --msg-template='{path}:{line}:{column}: {category}: {msg_id}: {msg} ({symbol})' "$1" | awk -F: 'BEGIN { OFS=":" } { if (NF == 6) { $3 += 1; print } }'; } && run }
    hook buffer BufWritePre .* %{
	    format
	    lint
	}
}

hook global WinSetOption filetype=terraform %{
    set window formatcmd 'terraform fmt -'
    map window insert <s-tab> '<a-;>   '
    map window insert <tab> '<a-;>   '
    set window indentwidth 2
    hook buffer BufWritePre .* %{format}
}

hook global WinSetOption filetype=sh %{
    set window formatcmd 'shfmt'
    hook buffer BufWritePre .* %{format}
}

hook global WinSetOption filetype=rust %{
    set window formatcmd 'rustfmt'
    hook buffer BufWritePre .* %{format}
}

hook global WinSetOption filetype=(c|cpp) %{
    # set window formatcmd 'clang-format --fallback-style=WebKit'
    # hook buffer BufWritePre .* %{format}
}

hook global WinSetOption filetype=yaml %{
    map window insert <s-tab> '<a-;>  '
    map window insert <tab> '<a-;>  '
    set window indentwidth 2
    set window formatcmd 'yamlfmt -'
}

hook global WinSetOption filetype=java %{
	map -docstring "println" window user P 'iSystem.out.println("");<esc>'
	map -docstring "printf" window user F 'iSystem.out.printf("");<esc>'

	set window formatcmd 'java -jar /home/aghani/.local/lib/google-java-format-1.9-all-deps.jar -a -'
	hook buffer BufWritePre .* %{format}
}

hook global WinSetOption filetype=latex %{
	hook buffer BufWritePost .* %{
		nop %sh{
			PDF="$(dirname "$kak_buffile")/$(basename "$kak_buffile" .tex).pdf"
			if [ -z "$(ps | grep "evince $PDF")" ]; then
				evince "$PDF" > /dev/null 2>&1 < /dev/null &
			fi
			cd "$(dirname "$kak_buffile")"
			latexmk -pdf &
		}
	}
}

map -docstring "edit .tmux.conf" global user t ':e ~/.tmux.conf<ret>'
map -docstring "edit kakrc" global user e ':e ~/.config/kak/kakrc<ret>'
map -docstring "edit bashrc" global user b ':e ~/.bashrc<ret>'
map -docstring "edit alacritty.yml" global user a ':e ~/.config/alacritty/alacritty.yml<ret>'
map -docstring "wl-paste" global user p '!xclip -selection clipboard -o<ret>'

hook global RegisterModified '"' %{ nop %sh{
    printf %s "$kak_main_reg_dquote" | xclip -selection clipboard >/dev/null 2>&1 &
}}

map global normal '#' ':comment-line<ret>'

map -docstring 'split vertically' global user d ':tmux-terminal-horizontal kak -c %val{session}<ret>'
map -docstring 'split horizontally' global user D ':tmux-terminal-vertical kak -c %val{session}<ret>'
map -docstring "kaktree" global user k ':kaktree-toggle<ret>'

map global normal ',' '<space>'
map global normal '<space>' ','
